AWSTemplateFormatVersion: 2010-09-09
Description: Simple EC2 instance creation to deploy a project from GitHub.
Resources:
  SimpleEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ed6534c7d6a8e78f
      SecurityGroupIds:
        - InstanceSecurityGroup.GroupId
      UserData:
        Fn::Base64: >
          #!/bin/bash

          yum update -y

          yum install -y git java-1.8.0-openjdk  # Instalar Git y Java

          cd /home/ec2-user

          git clone https://github.com/UrregoJontahan/test.git  # Clonar el repositorio desde GitHub

          cd test

          ./gradlew bootRun  # Ejecutar el proyecto (ajusta este comando según tu proyecto)
      Tags:
        - Key: Name
          Value: SimpleEC2Instance
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the simple EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: SimpleEC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: SimpleEC2Instance.PublicIp